### ISSUE TITLE
Unable to use this depenedency with JPMS

### ISSUE THREAD

**Issue by m4ttek** [micronaut-projects/micronaut-problem-json#289]
### Expected Behavior

Micronaut application should work with JPMS based application but it is not possible with this module due to problematic transitive dependency zalando-problem.

### Actual Behaviour

The same problem as mine is reported in https://github.com/zalando/problem/issues/357 and it has not been fixed since 2022.

### Environment Information

- JDK 20 with module-info defined

### Version

3.0.1 used with micronaut 4.0.0

**Comment by sdelamo** [comment]
I don't think we can fix it here. It has to be fixed in `zalando/problem`.

**Comment by timyates** [comment]
So, as mentioned in the issue, this is a problem with https://github.com/zalando/problem/issues/357

There's a wider discussion around Micronaut and JPMS going on as well 

https://github.com/micronaut-projects/micronaut-core/issues/6395

Which has been currently scheduled for Micronaut 5 (as it would be a breaking change)

Unfortunately I think we need both of these pieces for this to work.  So I'm moving this to Micronaut 5 and hoping the zalando issue is fixed by then 🤞

**Comment by m4ttek** [comment]
It seems that changes proposed in this PR https://github.com/zalando/problem/pull/483 will fix it.
